[package]
name = "dollhouse"
description = "A safe place for sharing your media files ğŸ€ğŸ "
repository = "https://github.com/Blooym/dollhouse"
authors = ["Blooym"]
version = "0.1.0"
edition = "2024"

[lints.rust]
unsafe_code = "forbid"

[profile.release]
codegen-units = 1
lto = true

[dependencies]
anyhow = "1.0.96"
axum = { version = "0.8.1", features = ["http2", "macros", "multipart"] }
axum-extra = { version = "0.10.0", features = ["typed-header"] }
blake3 = "1.6.0"
bytesize = "1.3.2"
clap = { version = "4.5.30", features = ["derive", "env", "string"] }
clap-duration = "0.1.11"
dirs = "6.0.0"
dotenvy = "0.15.7"
duration-human = "0.1.10"
hex = "0.4.3"
infer = "0.19.0"
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "net",
] }
tower-http = { version = "0.6.2", features = [
    "catch-panic",
    "normalize-path",
    "timeout",
    "trace",
    "fs",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
url = "2.5.4"
